default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: flow
  password: flow123

development:
  <<: *default
  database: flow-app-dev

test:
  <<: *default
  database: flow-app-test

production:
  <<: *default
  database: flow-app-prod
